name: Build JAR with Gradle (Java 8 - Corretto)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK (Corretto 8)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '8'
          cache: 'gradle'

      - name: Build JAR
        run: ./gradlew build --no-daemon

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Hephaestus-JAR
          path: build/libs/Hephaestus-1.0.0-SNAPSHOT-all.jar

